# Generated by Django 5.0.4 on 2026-05-24 17:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.IntegerField(choices=[(1, 'Scope 1'), (2, 'Scope 2'), (3, 'Scope 3')])),
                ('category', models.CharField(choices=[('fuel_diesel', 'Diesel Combustion'), ('fuel_petrol', 'Petrol Combustion'), ('fuel_natural_gas', 'Natural Gas Combustion'), ('electricity', 'Purchased Electricity'), ('flight_domestic', 'Flight – Domestic'), ('flight_short_haul', 'Flight – Short Haul'), ('flight_long_haul', 'Flight – Long Haul'), ('hotel_stay', 'Hotel Stay'), ('ground_transport', 'Ground Transport (Car/Rail)'), ('procurement', 'Procurement / Supply Chain')], max_length=50)),
                ('activity_date', models.DateField()),
                ('activity_quantity', models.DecimalField(decimal_places=6, max_digits=18)),
                ('activity_unit', models.CharField(max_length=50)),
                ('activity_description', models.TextField(blank=True)),
                ('emission_factor', models.DecimalField(decimal_places=8, max_digits=18)),
                ('emission_factor_source', models.CharField(max_length=255)),
                ('co2e_kg', models.DecimalField(decimal_places=4, max_digits=18)),
                ('source_system', models.CharField(max_length=100)),
                ('source_row_id', models.CharField(blank=True, max_length=255)),
                ('raw_data', models.JSONField(default=dict)),
                ('unit_conversion_applied', models.BooleanField(default=False)),
                ('unit_conversion_note', models.TextField(blank=True)),
                ('date_parse_note', models.TextField(blank=True)),
                ('review_status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('flagged', 'Flagged – Needs Clarification')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('is_flagged', models.BooleanField(default=False)),
                ('flag_reason', models.TextField(blank=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_records', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-activity_date'],
            },
        ),
        migrations.CreateModel(
            name='EmissionRecordEditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('edited_at', models.DateTimeField(auto_now_add=True)),
                ('field_name', models.CharField(max_length=100)),
                ('old_value', models.TextField()),
                ('new_value', models.TextField()),
                ('reason', models.TextField(blank=True)),
                ('edited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_log', to='emissions.emissionrecord')),
            ],
            options={
                'ordering': ['edited_at'],
            },
        ),
        migrations.CreateModel(
            name='IngestionBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('sap_flat_file', 'SAP Flat File (IDoc/XLSX export)'), ('utility_csv', 'Utility Portal CSV Export'), ('travel_api', 'Corporate Travel Platform (Navan/Concur JSON)')], max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('original_filename', models.CharField(blank=True, max_length=500)),
                ('raw_file', models.FileField(blank=True, null=True, upload_to='raw_uploads/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('row_count_raw', models.IntegerField(default=0)),
                ('row_count_accepted', models.IntegerField(default=0)),
                ('row_count_rejected', models.IntegerField(default=0)),
                ('error_log', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='emissions.organisation')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='emissions.ingestionbatch'),
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emission_records', to='emissions.organisation'),
        ),
        migrations.CreateModel(
            name='OrganisationMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('analyst', 'Analyst'), ('viewer', 'Viewer')], default='analyst', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='emissions.organisation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['organisation', 'scope', 'activity_date'], name='emissions_e_organis_63a65f_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['organisation', 'review_status'], name='emissions_e_organis_dac8b4_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['batch'], name='emissions_e_batch_i_f2aa5a_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['is_flagged'], name='emissions_e_is_flag_fd6be0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='organisationmembership',
            unique_together={('user', 'organisation')},
        ),
    ]
